### ISSUE TITLE
ghcide doesn't work with stack on Windows 10

### ISSUE THREAD

**Issue by nartamonov** [haskell/ghcide#68]
I've tried to run ghcide with default stack-based project but failed because of error `Inappropriate ioctl for device`:

```shell
λ stack -v-version
Version 2.1.3, Git revision 0fa51b9925decd937e4a993ad90cb686f88fa282 (7739 commits) x86_64 hpack-0.31.2
λ stack new ghcide-setup
...
λ cd ghcide-setup\
...
λ stack build hie-bios ghcide --copy-compiler-tool
...
λ stack exec ghcide
Starting ghcide (GHC v8.6)
C:\Dev\learning\ghcide-setup
[1/6] Finding hie-bios cradle
Cradle {cradleRootDir = "C:\\Dev\\learning\\ghcide-setup", cradleOptsProg = CradleAction: stack}

[2/6] Converting Cradle to GHC session
#!/usr/bin/env bash
if [ "$1" == "--interactive" ]; then
  pwd
  echo "$@"
else
  ghc "$@"
fi

ghcide.EXE: (ExitFailure 1,"stty: '\1057\1027\1057\8218\1056\176\1056\1029\1056\1169\1056\176\1057\1026\1057\8218\1056\1029\1057\8249\1056\8470 \1056\1030\1056\1030\1056\1109\1056\1169': Inappropriate ioctl for device\n","")
CallStack (from HasCallStack):
  error, called at src\HIE\Bios\Cradle.hs:217:18 in hie-bios-0.1.1-BtqPrxfQWIRF4Jj9iic9A:HIE.Bios.Cradle
```

**Comment by hsenag** [comment]
I don't think hie-bios, which ghcide uses to figure out how to run ghc, supports stack on Windows at the moment. For cabal, there's a windows exe that replaces the shell script you see quoted, but I don't think it was ever setup for stack.

The workaround would be to setup a "direct" cradle.

**Comment by cocreature** [comment]
Yeah I think @hsenag’s diagnosis is right. This needs to be fixed in `hie-bios`.

**Comment by nartamonov** [comment]
Should I open another bug in [mpickering/hie-bios](https://github.com/mpickering/hie-bios/) repository? I'm not sure if maintainers of ghcide and hie-bios are the same people...

**Comment by ndmitchell** [comment]
@nartamonov - we aren't the same people, but we watch each others repos a fair bit. In this case the problem is entirely on the hie-bios side, so yes, a ticket there would be appropriate.

**Comment by nartamonov** [comment]
The problem was fixed in mpickering/hie-bios#49.

**Comment by tuomohopia** [comment]
ghcide is supposed to be working on Windows 10 now? Not sure if I'm installing ghcide correctly, but on WIN10 I still get this `stty` problem:
```
ghcide.exe: CradleError (ExitFailure 1) ["Failed to parse result of calling stack","'stty' is not recognized as an internal or external command,","operable program or batch file."
```

**Comment by jneira** [comment]
@tuomohopia the workaround you commented here:https://github.com/haskell/haskell-ide-engine/issues/1428#issuecomment-547530794 doesnt work in ghcide case?
ghcide uses hie-bios to get compiler info and it calls to `stack` for it so the message and the workaround would work here.

**Comment by tuomohopia** [comment]
@jneira Thanks for reminding me, putting that .bat file in the project root dir did resolve it for me again!

For others hitting this problem on WIN10; I was able to run `ghcide` at the project root dir by doing that and also adding a `hie.yaml` file with the following contents:
```
cradle: {stack: {component: "my-project-name:lib" }}
```

More info here:
https://github.com/mpickering/hie-bios#readme

**Comment by jneira** [comment]
> putting that .bat file in the project root dir did resolve it for me again!

Out of curiosity: doesnt putting it in %PATH%, fix it in general?

**Comment by ndmitchell** [comment]
Sounds like hie-bios should be working around the stty issue itself?

**Comment by ndmitchell** [comment]
Reopening until someone fixes something - adding a .bat file isn't a good enough answer

**Comment by ndmitchell** [comment]
Note that the solution can either be in hie-bios ignoring the stty issue, or Stack not producing it (https://github.com/commercialhaskell/stack/pull/4968), but it's a grim problem at the moment.

**Comment by tuomohopia** [comment]
@jneira yeah it does, I don't know how I managed to lose the file on my `PATH`. 
I hope they make the decision on how to fix this at Stack's end.

**Comment by jneira** [comment]
the `stty` thing has been resolved in stack with https://github.com/commercialhaskell/stack/pull/5183, so using a new enough stack version should fix the issue

**Comment by jneira** [comment]
We still should remove or update the warning in the docs
